; Semantic PSO-1 recipe fragment.
[shape018]
kind=glyph
part=labels
flags=visible
x0=-7300
y0=-1900
a=350
b=500
i0=49

[shape019]
kind=glyph
part=labels
flags=visible
x0=-6800
y0=-1900
a=350
b=500
i0=48

[shape020]
kind=glyph
part=labels
flags=visible
x0=6200
y0=-1900
a=350
b=500
i0=49

[shape021]
kind=glyph
part=labels
flags=visible
x0=6700
y0=-1900
a=350
b=500
i0=48
