#ifndef BLANK3D_WEAPON_PRESENTATION_H
#define BLANK3D_WEAPON_PRESENTATION_H
#include "gweaponpresentation89.h"
typedef GWeaponPresentation89 Blank3DWeaponPresentation;
typedef GWeaponPresentationRegistry89 Blank3DWeaponPresentationRegistry;
#define B3D_WPRES_MAX_PROFILES GWPRES89_MAX_PROFILES
#define B3D_WPRES_NAME_CAP GWPRES89_NAME_CAP
#define B3D_WPRES_PATH_CAP GWPRES89_PATH_CAP
#define B3D_MECHANISM_FIXED GWPRES89_MECHANISM_FIXED
#define B3D_MECHANISM_SLIDE_MAGAZINE GWPRES89_MECHANISM_SLIDE_MAGAZINE
#define B3D_MECHANISM_BOLT_MAGAZINE GWPRES89_MECHANISM_BOLT_MAGAZINE
#define B3D_MECHANISM_PUMP_TUBE GWPRES89_MECHANISM_PUMP_TUBE
#define B3D_MECHANISM_REVOLVER GWPRES89_MECHANISM_REVOLVER
#define B3D_MECHANISM_GATLING_BELT GWPRES89_MECHANISM_GATLING_BELT
#define B3D_MECHANISM_ELASTIC GWPRES89_MECHANISM_ELASTIC
#define B3D_WEAPON_MODEL_GENERIC GWPRES89_MODEL_GENERIC
#define blank3d_weapon_presentation_registry_init gweaponpresentation89_registry_init
#define blank3d_weapon_presentation_defaults gweaponpresentation89_defaults
#define blank3d_weapon_presentation_find gweaponpresentation89_find
#define blank3d_weapon_presentation_mechanism_from_text gweaponpresentation89_mechanism_from_text
#define blank3d_weapon_presentation_mechanism_name gweaponpresentation89_mechanism_name
#endif
