#ifndef BLANK3D_WEAPON_LOADOUT_H
#define BLANK3D_WEAPON_LOADOUT_H
#include "gweaponloadout89.h"
typedef GWeaponCatalogEntry89 Blank3DWeaponCatalogEntry;
typedef GWeaponCatalog89 Blank3DWeaponCatalog;
typedef GWeaponLoadout89 Blank3DPlayerWeaponLoadout;
#define B3D_WLOAD_MAX_WEAPONS GWLOAD89_MAX_WEAPONS
#define B3D_WLOAD_NAME_CAP GWLOAD89_NAME_CAP
#define B3D_WLOAD_PATH_CAP GWLOAD89_PATH_CAP
#define blank3d_weapon_catalog_defaults gweaponloadout89_catalog_defaults
#define blank3d_player_weapon_loadout_defaults gweaponloadout89_defaults
#define blank3d_weapon_catalog_find_id gweaponloadout89_catalog_find_id
#endif
