#ifndef BLANK3D_SNIPER_H
#define BLANK3D_SNIPER_H
#include "gweaponsniper89.h"
typedef GWeaponSniper89 Blank3DSniper;
#define B3D_SCOPE_MAX_ANIM_SHAPES GWSN89_SCOPE_MAX_ANIM_SHAPES
#define blank3d_sniper_init gweaponsniper89_init
#define blank3d_sniper_set_screen gweaponsniper89_set_screen
#define blank3d_sniper_update gweaponsniper89_update
#define blank3d_sniper_fov_deg_x100 gweaponsniper89_fov_deg_x100
#define blank3d_sniper_sensitivity_pct gweaponsniper89_sensitivity_pct
#define blank3d_sniper_sway_yaw_x1000 gweaponsniper89_sway_yaw_x1000
#define blank3d_sniper_sway_pitch_x1000 gweaponsniper89_sway_pitch_x1000
#define blank3d_sniper_is_scoped gweaponsniper89_is_scoped
#define blank3d_sniper_scope_recipe_loaded gweaponsniper89_scope_recipe_loaded
#define blank3d_sniper_scope_animation_loaded gweaponsniper89_scope_animation_loaded
#define blank3d_sniper_trigger_event gweaponsniper89_trigger_event
#define blank3d_sniper_scope_last_error gweaponsniper89_scope_last_error
#define blank3d_sniper_register_scope_provider gweaponsniper89_register_scope_provider
#define blank3d_sniper_emit gweaponsniper89_emit
#endif
