#ifndef BLANK3D_PROJECTILE_MESH_H
#define BLANK3D_PROJECTILE_MESH_H

#include "../vendor/giffany_shapes3d/g3d_shapes.h"

#ifdef __cplusplus
extern "C" {
#endif

#define B3D_PROJECTILE_MESH_COUNT 17
#define B3D_PROJECTILE_VERTEX_CAPACITY 512
#define B3D_PROJECTILE_INDEX_CAPACITY 2304

#define B3D_CASING_MESH_COUNT 5
#define B3D_CASING_VERTEX_CAPACITY 192
#define B3D_CASING_INDEX_CAPACITY 896

/*
 * Build one renderer mesh from the actual weapon-stack projectile libraries.
 * Mesh IDs are the IDs published by gweapon89 profiles:
 *   1 pistol, 2 machine gun, 3 shotgun pellet, 4 magnum,
 *   5 sniper, 6 40 mm grenade, 7 rocket, 8 Gatling/MG projectile,
 *   9 slingshot stone generated by Giffany Shapes3D primitives,
 *   10 hand grenade from ghandgrenade3d89 (not a 40 mm round),
 *   11 Shango/orbital energy cylinder generated with Shapes3D,
 *   12 homing tandem rocket from rocketmeshes (RPG7 PG7VR geometry),
 *   13 low-poly flame cube generated with Shapes3D. expandiblefire89 drives
 *      its runtime growth; the immutable mesh stays presentation-only data.
 *   14 Buster lemon, 15 charge-1, 16 charge-2, 17 charge-3 energy bolts.
 * Every output mesh is normalized to local +Z = direction of travel.
 */
int blank3d_projectile_mesh_build(int mesh_id,
                                  g3d_mesh *mesh,
                                  g3d_vertex *vertices,
                                  unsigned short vertex_capacity,
                                  g3d_index *indices,
                                  unsigned short index_capacity);

const char *blank3d_projectile_mesh_name(int mesh_id);

/*
 * Casing mesh IDs are deliberately separate from projectile mesh IDs:
 *   1 pistol, 2 machine gun / Gatling, 3 shotgun, 4 magnum, 5 sniper.
 * The shell library also uses local +Z as its long axis.
 */
int blank3d_casing_mesh_build(int mesh_id,
                              g3d_mesh *mesh,
                              g3d_vertex *vertices,
                              unsigned short vertex_capacity,
                              g3d_index *indices,
                              unsigned short index_capacity);

const char *blank3d_casing_mesh_name(int mesh_id);

#ifdef __cplusplus
}
#endif

#endif
