#ifndef BLANK3D_BALLISTICS_H
#define BLANK3D_BALLISTICS_H
#include "gweaponballistics89.h"
#define blank3d_ballistics_align_event_to_view gweaponballistics89_align_event_to_view
#define blank3d_ballistics_resolve_launch gweaponballistics89_resolve_launch
#endif
