#ifndef BLANK3D_CROSSHAIR_H
#define BLANK3D_CROSSHAIR_H
#include "gweaponcrosshair89.h"
typedef GWeaponCrosshair89 Blank3DCrosshair;
#define B3D_CROSSHAIR_DEFAULT_ROOT GWC89_DEFAULT_ROOT
#define B3D_CROSSHAIR_ANIM_TICK_MS GWC89_ANIM_TICK_MS
#define blank3d_crosshair_init gweaponcrosshair89_init
#define blank3d_crosshair_set_primitive_provider gweaponcrosshair89_set_primitive_provider
#define blank3d_crosshair_set_primitive_fallback gweaponcrosshair89_set_primitive_fallback
#define blank3d_crosshair_providers gweaponcrosshair89_providers
#define blank3d_crosshair_find_preset gweaponcrosshair89_find_preset
#define blank3d_crosshair_set_preset_id gweaponcrosshair89_set_preset_id
#define blank3d_crosshair_set_preset_name gweaponcrosshair89_set_preset_name
#define blank3d_crosshair_preset_name gweaponcrosshair89_preset_name
#define blank3d_crosshair_trigger_event gweaponcrosshair89_trigger_event
#define blank3d_crosshair_animation_modifier gweaponcrosshair89_animation_modifier
#define blank3d_crosshair_draw gweaponcrosshair89_draw
#endif
