#ifndef BLANK3D_UNIVERSAL_AIM_H
#define BLANK3D_UNIVERSAL_AIM_H
#include "gweaponaim89.h"
#include "blank3d_weapon_modules.h"
#include "blank3d_ballistics.h"
typedef GWeaponAimFrame89 Blank3DUniversalAimFrame;
#define B3D_UNIVERSAL_AIM_ZERO_DISTANCE GWA89_ZERO_DISTANCE
#define B3D_UNIVERSAL_AIM_CLEARANCE GWA89_CLEARANCE
#define blank3d_universal_aim_build gweaponaim89_build
#define blank3d_universal_aim_apply_pose gweaponaim89_apply_pose
#define blank3d_universal_aim_guard_direction gweaponaim89_guard_direction
#define blank3d_universal_aim_finalize_event gweaponaim89_finalize_event
#endif
