#ifndef BLANK3D_MECHANICAL_WEAPON_H
#define BLANK3D_MECHANICAL_WEAPON_H
#include "gmechanicalweapon89.h"
typedef GMechanicalWeapon89 Blank3DMechanicalWeapon;
#define B3D_MECH89_MAX_PACKETS GMW89_MAX_PACKETS
#define B3D_MECH89_TICK_MS GMW89_TICK_MS
#define B3D_MECH89_MESH_BODY GMW89_MESH_BODY
#define B3D_MECH89_MESH_SLIDE GMW89_MESH_SLIDE
#define B3D_MECH89_MESH_MAGAZINE GMW89_MESH_MAGAZINE
#define B3D_MECH89_MESH_BARREL GMW89_MESH_BARREL
#define B3D_MECH89_MESH_COUNT GMW89_MESH_COUNT
#define B3D_MECH89_PART_ROOT GMW89_PART_ROOT
#define B3D_MECH89_PART_RECOIL GMW89_PART_RECOIL
#define B3D_MECH89_PART_BODY GMW89_PART_BODY
#define B3D_MECH89_PART_SLIDE GMW89_PART_SLIDE
#define B3D_MECH89_PART_MAGAZINE GMW89_PART_MAGAZINE
#define B3D_MECH89_PART_BARREL GMW89_PART_BARREL
#define B3D_MECH89_PART_MUZZLE_SOCKET GMW89_PART_MUZZLE_SOCKET
#define B3D_MECH89_ACTION_FIRE GMW89_ACTION_FIRE
#define B3D_MECH89_EVENT_SLIDE_REAR GMW89_EVENT_SLIDE_REAR
#define blank3d_mechanical_weapon_init gmechanicalweapon89_init
#define blank3d_mechanical_weapon_init_profile gmechanicalweapon89_init_profile
#define blank3d_mechanical_weapon_set_attachment gmechanicalweapon89_set_attachment
#define blank3d_mechanical_weapon_set_weapon gmechanicalweapon89_set_weapon
#define blank3d_mechanical_weapon_set_reload gmechanicalweapon89_set_reload
#define blank3d_mechanical_weapon_trigger_fire gmechanicalweapon89_trigger_fire
#define blank3d_mechanical_weapon_update gmechanicalweapon89_update
#define blank3d_mechanical_weapon_packet_count gmechanicalweapon89_packet_count
#define blank3d_mechanical_weapon_packet gmechanicalweapon89_packet
#define blank3d_mechanical_weapon_part_pose gmechanicalweapon89_part_pose
#define blank3d_mechanical_weapon_muzzle_socket gmechanicalweapon89_muzzle_socket
#define blank3d_mechanical_weapon_muzzle_world gmechanicalweapon89_muzzle_world
#define blank3d_mechanical_weapon_status gmechanicalweapon89_status
#endif
