#ifndef BLANK3D_SHOTGUN_H
#define BLANK3D_SHOTGUN_H
#include "gshotgun89.h"
#define B3D_SHOTGUN_WEAPON_ID GSHOT89_WEAPON_ID
#define B3D_SHOTGUN_PELLET_COUNT GSHOT89_PELLET_COUNT
#define B3D_SHOTGUN_MIN_LIFE_MS GSHOT89_MIN_LIFE_MS
#define blank3d_shotgun_prepare_pellet gshotgun89_prepare_pellet
#endif
